import type { SpriteResolution } from '../ui/stores/settings';


// Low-res sprite URLs (32px)
const lowResSprites = import.meta.glob<string>(
  '../assets/sprites/**/*.png',
  { eager: true, query: '?url', import: 'default' }
);

// High-res sprite URLs (256px)
const highResSprites = import.meta.glob<string>(
  '../assets/sprites-hires/**/*.png',
  { eager: true, query: '?url', import: 'default' }
);

/**
 * Returns the CDN-relative URLs for a biome's packed texture atlas.
 * Atlas files are generated by the ComfyUI sprite pipeline and packed via scripts/pack-atlas.mjs.
 * Naming convention: mine_atlas_<biomeId>.{json,webp}
 *
 * DD-V2-189: TextureAtlasLRU enforces the 3-atlas max; this function provides the URLs.
 *
 * @param biomeId - The biome ID (e.g. 'surface', 'volcanic')
 * @returns Object with json and image URL paths
 */
export function getBiomeAtlasUrl(biomeId: string): { json: string; image: string } {
  const base = import.meta.env.VITE_ASSET_BASE_URL ?? ''
  return {
    json:  `${base}/assets/atlases/mine_atlas_${biomeId}.json`,
    image: `${base}/assets/atlases/mine_atlas_${biomeId}.webp`,
  }
}

/**
 * Returns the Phaser texture key for a biome's packed atlas.
 *
 * @param biomeId - The biome ID (e.g. 'surface', 'volcanic')
 * @returns The texture key string used in Phaser's texture manager
 */
export function getBiomeAtlasKey(biomeId: string): string {
  return `mine_atlas_${biomeId}`
}

/**
 * Detects WebP support at runtime. True on Chrome/Edge/Firefox 65+; false on older Safari.
 *
 * @returns True if WebP is supported in the current browser
 */
export function supportsWebP(): boolean {
  try {
    const c = document.createElement('canvas')
    c.width = 1; c.height = 1
    return c.toDataURL('image/webp').startsWith('data:image/webp')
  } catch (_) { return false }
}

/**
 * Get sprite URLs for the specified resolution.
 * Extracts sprite keys from filenames and returns a mapping of key → URL.
 * @param resolution - The desired sprite resolution ('low' or 'high')
 * @returns A record mapping sprite keys to their URL strings
 */
export function getSpriteUrls(resolution: SpriteResolution): Record<string, string> {
  const spriteMap = resolution === 'high' ? highResSprites : lowResSprites;
  const result: Record<string, string> = {};

  for (const [path, url] of Object.entries(spriteMap)) {
    // Extract filename without extension
    // e.g., '../assets/sprites/tiles/tile_dirt.png' → 'tile_dirt'
    const filename = path.split('/').pop() || '';
    const spriteKey = filename.replace(/\.png$/, '');
    result[spriteKey] = url;
  }

  return result;
}
