name = "recall-rogue"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

[site]
bucket = "./dist"

[env.preview]
name = "recall-rogue-preview"

[env.production]
name = "recall-rogue-production"
