import type { CardType } from '../../data/card-types'

// ============================================================
// Icon Path Registry
// ============================================================

// All icons are PNG files in /assets/sprites/icons/
// Generated by sprite-gen/scripts/generate-sprites.mjs from icon-registry.json

/**
 * Get the icon image path for a card type.
 * @param type - The card type (attack, shield, utility, buff, debuff, wild, heal, regen)
 * @returns The path to the card type icon (PNG format)
 */
export function getCardTypeIconPath(type: CardType | 'heal' | 'regen'): string {
	return `/assets/sprites/icons/icon_cardtype_${type}.png`
}

/**
 * Ordered candidate chain for card type icons.
 * Consumers should try entries in order and fall back to emoji only if all fail.
 */
export function getCardTypeIconCandidates(type: CardType | 'heal' | 'regen'): string[] {
	return [
		`/assets/sprites/icons/icon_cardtype_${type}.png`,
		`/assets/sprites/icons/icon_cardtype_${type}.webp`,
		'/assets/sprites/icons/icon_ui_card_fallback.png',
	]
}

/**
 * Emoji fallback for card types (used when icon fails to load).
 * @param type - The card type
 * @returns An emoji representation of the card type
 */
export function getCardTypeEmoji(type: string): string {
	const EMOJI_MAP: Record<string, string> = {
		attack: '⚔️',
		shield: '🛡️',
		utility: '⭐',
		buff: '⬆️',
		debuff: '⬇️',
		wild: '💎',
		heal: '💚',
		regen: '➕',
	}
	return EMOJI_MAP[type] ?? '🃏'
}

/**
 * Get the relic icon path by relic ID.
 * @param relicId - The relic identifier
 * @returns The path to the relic icon
 */
export function getRelicIconPath(relicId: string): string {
	return `/assets/sprites/icons/icon_relic_${relicId}.png`
}

/**
 * Get the enemy intent icon path.
 * When metadata is provided, picks a more specific weapon/shield icon
 * based on status effects, damage value, or hit count.
 */
export function getIntentIconPath(
  intentType: string,
  meta?: { statusEffect?: string; value?: number; hitCount?: number },
): string {
  // Enriched attack icons based on status effect or damage
  if (intentType === 'attack' && meta) {
    if (meta.statusEffect === 'poison') return '/assets/sprites/icons/icon_reward_venom_fang.png'
    if (meta.statusEffect === 'burn') return '/assets/sprites/icons/icon_reward_arc_scroll.png'
    if (meta.statusEffect === 'bleed') return '/assets/sprites/icons/icon_reward_hunter_bow.png'
    if (meta.statusEffect === 'weakness' || meta.statusEffect === 'vulnerable') return '/assets/sprites/icons/icon_reward_hex_totem.png'
    if (meta.value != null && meta.value > 10) return '/assets/sprites/icons/icon_reward_war_axe.png'
    if (meta.value != null && meta.value <= 4) return '/assets/sprites/icons/icon_reward_rust_dagger.png'
  }

  const INTENT_PATH_MAP: Record<string, string> = {
    attack: '/assets/sprites/icons/icon_cardtype_attack.png',
    multi_attack: '/assets/sprites/icons/icon_reward_twin_blades.png',
    defend: '/assets/sprites/icons/icon_reward_round_shield.png',
    buff: '/assets/sprites/icons/icon_reward_surge_sigil.png',
    debuff: '/assets/sprites/icons/icon_reward_snare_thread.png',
    heal: '/assets/sprites/icons/icon_reward_tool_kit.png',
    charge: '/assets/sprites/icons/icon_reward_comet_shard.png',
  }
  return INTENT_PATH_MAP[intentType] ?? '/assets/sprites/icons/icon_ui_unknown.png'
}

/**
 * Get the hub navigation icon path.
 * @param navKey - The nav item key (hub, library, journal, profile, settings, social, start)
 * @returns The path to the nav icon
 */
export function getNavIconPath(navKey: string): string {
	return `/assets/sprites/icons/icon_nav_${navKey}.png`
}


/**
 * Get the archetype icon path.
 * @param archetypeId - The archetype identifier (balanced, aggressive, defensive, control, hybrid)
 * @returns The path to the archetype icon
 */
export function getArchetypeIconPath(archetypeId: string): string {
	return `/assets/sprites/icons/icon_archetype_${archetypeId}.png`
}


/**
 * Get the leaderboard ranking icon path.
 * @param key - The leaderboard type (deepest_dive, facts_mastered, longest_streak, knowledge_tree, quiz_accuracy, total_dives, gold_medal, silver_medal, bronze_medal)
 * @returns The path to the leaderboard icon
 */
export function getLeaderboardIconPath(key: string): string {
	return `/assets/sprites/icons/icon_lb_${key}.png`
}

/**
 * Get the mystery event icon path.
 * @param effectType - The mystery event effect type (choice, damage, free_card, heal, nothing)
 * @returns The path to the mystery event icon
 */
export function getMysteryEventIconPath(effectType: string): string {
	return `/assets/sprites/icons/icon_mystery_${effectType}.png`
}


/**
 * Get a miscellaneous UI icon path.
 * @param elementId - The UI element identifier (e.g., 'card_fallback', 'loading', 'trophy')
 * @returns The path to the UI icon
 */
export function getUIIconPath(elementId: string): string {
	return `/assets/sprites/icons/icon_ui_${elementId}.png`
}

/**
 * Get the domain icon path (for Knowledge Library categories).
 * @param domainId - The domain identifier (e.g., 'animals_wildlife', 'space_astronomy')
 * @returns The path to the domain icon
 */
export function getDomainIconPath(domainId: string): string {
	return `/assets/sprites/icons/icon_domain_${domainId}.png`
}

/**
 * Get the gold coin icon path (single coin, for HUD/UI display).
 * Use this for small inline gold displays.
 * @returns The path to the gold coin icon (WebP format)
 */
export function getGoldCoinIconPath(): string {
  return '/assets/sprites/icons/icon_currency_gold.webp'
}

/**
 * Get the grey matter (persistent hub currency) icon path.
 * @returns The path to the grey matter icon (WebP format)
 */
export function getGreyMatterIconPath(): string {
  return '/assets/sprites/icons/icon_grey_matter.webp'
}

// ============================================================
// Fallback emoji maps (used when icons fail to load)
// ============================================================

const NAV_EMOJI: Record<string, string> = {
	hub: '🏃',
	library: '📖',
	social: '🤝',
	settings: '⚙️',
	profile: '👤',
	journal: '📜',
	start: '▶️',
}

/**
 * Get emoji fallback for navigation items.
 * @param key - The nav item key
 * @returns An emoji representation of the nav item
 */
export function getNavEmoji(key: string): string {
	return NAV_EMOJI[key] ?? '❓'
}


const ARCHETYPE_EMOJI: Record<string, string> = {
	balanced: '⚖️',
	aggressive: '⚔️',
	defensive: '🛡️',
	control: '🧠',
	hybrid: '🧩',
}

/**
 * Get emoji fallback for archetypes.
 * @param key - The archetype identifier
 * @returns An emoji representation of the archetype
 */
export function getArchetypeEmoji(key: string): string {
	return ARCHETYPE_EMOJI[key] ?? '❓'
}

const LEADERBOARD_EMOJI: Record<string, string> = {
	deepest_dive: '⛏️',
	facts_mastered: '🧠',
	longest_streak: '🔥',
	knowledge_tree: '🌳',
	quiz_accuracy: '🎯',
	total_dives: '🏊',
	gold_medal: '🥇',
	silver_medal: '🥈',
	bronze_medal: '🥉',
}

/**
 * Get emoji fallback for leaderboard rankings.
 * @param key - The leaderboard type
 * @returns An emoji representation of the ranking
 */
export function getLeaderboardEmoji(key: string): string {
	return LEADERBOARD_EMOJI[key] ?? '🏆'
}


const MYSTERY_EMOJI: Record<string, string> = {
	choice: '❓',
	damage: '💥',
	free_card: '🎁',
	heal: '💚',
	nothing: '⊘',
}

/**
 * Get emoji fallback for mystery events.
 * @param effectType - The mystery event effect type
 * @returns An emoji representation of the event
 */
export function getMysteryEventEmoji(effectType: string): string {
	return MYSTERY_EMOJI[effectType] ?? '❓'
}
