import type { CardType } from '../../data/card-types'
import type { StatusEffectType } from '../../data/statusEffects'

// ============================================================
// Icon Path Registry
// ============================================================

// All icons are PNG files in /assets/sprites/icons/
// Generated by sprite-gen/scripts/generate-sprites.mjs from icon-registry.json

/**
 * Get the icon image path for a card type.
 * @param type - The card type (attack, shield, utility, buff, debuff, wild, heal, regen)
 * @returns The path to the card type icon (PNG format)
 */
export function getCardTypeIconPath(type: CardType | 'heal' | 'regen'): string {
	return `/assets/sprites/icons/icon_cardtype_${type}.png`
}

/**
 * Ordered candidate chain for card type icons.
 * Consumers should try entries in order and fall back to emoji only if all fail.
 */
export function getCardTypeIconCandidates(type: CardType | 'heal' | 'regen'): string[] {
	return [
		`/assets/sprites/icons/icon_cardtype_${type}.png`,
		`/assets/sprites/icons/icon_cardtype_${type}.webp`,
		'/assets/sprites/icons/icon_ui_card_fallback.png',
	]
}

/**
 * Emoji fallback for card types (used when icon fails to load).
 * @param type - The card type
 * @returns An emoji representation of the card type
 */
export function getCardTypeEmoji(type: string): string {
	const EMOJI_MAP: Record<string, string> = {
		attack: '⚔️',
		shield: '🛡️',
		utility: '⭐',
		buff: '⬆️',
		debuff: '⬇️',
		wild: '💎',
		heal: '💚',
		regen: '➕',
	}
	return EMOJI_MAP[type] ?? '🃏'
}

/**
 * Get the reward altar variant icon path.
 * @param key - The reward icon key (e.g., 'arc_scroll', 'hunter_bow')
 * @returns The path to the reward icon
 */
export function getRewardIconPath(key: string): string {
	return `/assets/sprites/icons/icon_reward_${key}.png`
}

/**
 * Get the relic icon path by relic ID.
 * @param relicId - The relic identifier
 * @returns The path to the relic icon
 */
export function getRelicIconPath(relicId: string): string {
	return `/assets/sprites/icons/icon_relic_${relicId}.png`
}

/**
 * Get the V2 relic icon path (for newer relic designs).
 * @param relicId - The V2 relic identifier (with rc_ prefix, e.g., 'rc_pathfinder_boots')
 * @returns The path to the V2 relic icon
 */
export function getRelicV2IconPath(relicId: string): string {
	// V2 relics may have IDs like 'rc_pathfinder_boots' — strip prefix for filename
	const cleanId = relicId.replace(/^r[clr]_/, '')
	return `/assets/sprites/icons/icon_relic_v2_${cleanId}.png`
}

/**
 * Get the V1 relic icon path (for legacy relic designs).
 * @param relicId - The V1 relic identifier
 * @returns The path to the V1 relic icon
 */
export function getRelicV1IconPath(relicId: string): string {
	return `/assets/sprites/icons/icon_relic_v1_${relicId}.png`
}

/**
 * Get the status effect icon path.
 * @param type - The status effect type (poison, regen, strength, weakness, vulnerable, immunity)
 * @returns The path to the status effect icon
 */
export function getStatusEffectIconPath(type: StatusEffectType): string {
	return `/assets/sprites/icons/icon_status_${type}.png`
}

/**
 * Get the enemy intent icon path.
 * @param intentType - The intent type (attack, multi_attack, defend, buff, debuff, heal)
 * @returns The path to the intent icon
 */
export function getIntentIconPath(intentType: string): string {
	// Map intent types to icon paths
	const INTENT_PATH_MAP: Record<string, string> = {
		attack: '/assets/sprites/icons/icon_cardtype_attack.png',
		multi_attack: '/assets/sprites/icons/icon_intent_multi_attack.png',
		defend: '/assets/sprites/icons/icon_cardtype_shield.png',
		buff: '/assets/sprites/icons/icon_intent_buff_self.png',
		debuff: '/assets/sprites/icons/icon_intent_debuff_player.png',
		heal: '/assets/sprites/icons/icon_cardtype_heal.png',
	}
	return INTENT_PATH_MAP[intentType] ?? '/assets/sprites/icons/icon_ui_unknown.png'
}

/**
 * Get the hub navigation icon path.
 * @param navKey - The nav item key (hub, library, journal, profile, settings, social, start)
 * @returns The path to the nav icon
 */
export function getNavIconPath(navKey: string): string {
	return `/assets/sprites/icons/icon_nav_${navKey}.png`
}


/**
 * Get the archetype icon path.
 * @param archetypeId - The archetype identifier (balanced, aggressive, defensive, control, hybrid)
 * @returns The path to the archetype icon
 */
export function getArchetypeIconPath(archetypeId: string): string {
	return `/assets/sprites/icons/icon_archetype_${archetypeId}.png`
}


/**
 * Get the leaderboard ranking icon path.
 * @param key - The leaderboard type (deepest_dive, facts_mastered, longest_streak, knowledge_tree, quiz_accuracy, total_dives, gold_medal, silver_medal, bronze_medal)
 * @returns The path to the leaderboard icon
 */
export function getLeaderboardIconPath(key: string): string {
	return `/assets/sprites/icons/icon_lb_${key}.png`
}

/**
 * Get the mystery event icon path.
 * @param effectType - The mystery event effect type (choice, damage, free_card, heal, nothing)
 * @returns The path to the mystery event icon
 */
export function getMysteryEventIconPath(effectType: string): string {
	return `/assets/sprites/icons/icon_mystery_${effectType}.png`
}


/**
 * Get a miscellaneous UI icon path.
 * @param elementId - The UI element identifier (e.g., 'card_fallback', 'loading', 'trophy')
 * @returns The path to the UI icon
 */
export function getUIIconPath(elementId: string): string {
	return `/assets/sprites/icons/icon_ui_${elementId}.png`
}

/**
 * Get the enemy power badge icon path.
 * @param powerId - The power identifier (e.g., 'charge_resistant', 'chain_vulnerable')
 * @returns The path to the power badge icon
 */
export function getEnemyPowerIconPath(powerId: string): string {
	return `/assets/sprites/icons/icon_power_${powerId}.png`
}

/**
 * Get the domain icon path (for Knowledge Library categories).
 * @param domainId - The domain identifier (e.g., 'animals_wildlife', 'space_astronomy')
 * @returns The path to the domain icon
 */
export function getDomainIconPath(domainId: string): string {
	return `/assets/sprites/icons/icon_domain_${domainId}.png`
}

/**
 * Gold tier thresholds — matches gold_tiers.json in reward_room assets.
 * Returns the appropriate gold pile icon based on currency amount.
 */
const GOLD_TIERS = [
  { min: 1, max: 10, tier: 0 },
  { min: 11, max: 30, tier: 1 },
  { min: 31, max: 60, tier: 2 },
  { min: 61, max: 100, tier: 3 },
  { min: 101, max: 200, tier: 4 },
  { min: 201, max: Infinity, tier: 5 },
] as const

/**
 * Get the gold tier icon path based on amount.
 * Higher amounts show larger gold piles (6 tiers: 0–5).
 * @param amount - The gold amount to determine tier for
 * @returns The path to the appropriate gold tier icon (WebP format)
 */
export function getGoldTierIconPath(amount: number): string {
  const entry = GOLD_TIERS.find(t => amount >= t.min && amount <= t.max)
  const tier = entry?.tier ?? 5
  return `/assets/reward_room/gold_tier_${tier}.webp`
}

/**
 * Get the gold coin icon path (single coin, for HUD/UI display).
 * Use this for small inline gold displays. Use getGoldTierIconPath() for reward screens.
 * @returns The path to the gold coin icon (WebP format)
 */
export function getGoldCoinIconPath(): string {
  return '/assets/sprites/icons/icon_currency_gold.webp'
}

/**
 * Get the grey matter (persistent hub currency) icon path.
 * @returns The path to the grey matter icon (WebP format)
 */
export function getGreyMatterIconPath(): string {
  return '/assets/sprites/icons/icon_grey_matter.webp'
}

// ============================================================
// Fallback emoji maps (used when icons fail to load)
// ============================================================

const NAV_EMOJI: Record<string, string> = {
	hub: '🏃',
	library: '📖',
	social: '🤝',
	settings: '⚙️',
	profile: '👤',
	journal: '📜',
	start: '▶️',
}

/**
 * Get emoji fallback for navigation items.
 * @param key - The nav item key
 * @returns An emoji representation of the nav item
 */
export function getNavEmoji(key: string): string {
	return NAV_EMOJI[key] ?? '❓'
}


const ARCHETYPE_EMOJI: Record<string, string> = {
	balanced: '⚖️',
	aggressive: '⚔️',
	defensive: '🛡️',
	control: '🧠',
	hybrid: '🧩',
}

/**
 * Get emoji fallback for archetypes.
 * @param key - The archetype identifier
 * @returns An emoji representation of the archetype
 */
export function getArchetypeEmoji(key: string): string {
	return ARCHETYPE_EMOJI[key] ?? '❓'
}

const LEADERBOARD_EMOJI: Record<string, string> = {
	deepest_dive: '⛏️',
	facts_mastered: '🧠',
	longest_streak: '🔥',
	knowledge_tree: '🌳',
	quiz_accuracy: '🎯',
	total_dives: '🏊',
	gold_medal: '🥇',
	silver_medal: '🥈',
	bronze_medal: '🥉',
}

/**
 * Get emoji fallback for leaderboard rankings.
 * @param key - The leaderboard type
 * @returns An emoji representation of the ranking
 */
export function getLeaderboardEmoji(key: string): string {
	return LEADERBOARD_EMOJI[key] ?? '🏆'
}


const MYSTERY_EMOJI: Record<string, string> = {
	choice: '❓',
	damage: '💥',
	free_card: '🎁',
	heal: '💚',
	nothing: '⊘',
}

/**
 * Get emoji fallback for mystery events.
 * @param effectType - The mystery event effect type
 * @returns An emoji representation of the event
 */
export function getMysteryEventEmoji(effectType: string): string {
	return MYSTERY_EMOJI[effectType] ?? '❓'
}
